[instagram team] SOOO MANY EDIT!
kosslab-kr/kosshack2016 pull request #19
Opened 2016-09-27 16:54 UTC by MuhunKim

# `daily/01_instagram/README.md`
* Fix the soooo many typo
* Lowercase to uppercase in First letter of a English string
* SOOO MANY EDIT!
 * Create Docs Group Goals
 * Add Daily Report @MuhunKim in 9/26~9/27
 * etc..

# `index.html`
```html
<p><span class="text-primary" id="updateTime">업데이트 시간</span></p>
```

2016-09-27 17:37 UTC, LeeTaeSoon commented
a few line are ```Group Goal```  and  a few line are ```Team Goal```

2016-09-27 17:48 UTC, MuhunKim commented
@LeeTaeSoon 	solve : d1fa779

2016-09-28 01:57 UTC, JeffGuKang commented on daily/01_Instagram/README.md
> +  - 조승윤
Use tab for the nested list.

2016-09-28 01:58 UTC, JeffGuKang requested changes
`npm` is written lowercase always.
Tab has used for Nested list instead of spaces. 

Nested list는 현재 tab으로 구분하고 있습니다. (tab으로 만든  간격은 조절이 가능합니다. )
2차 목표는 회의 후 넣으려고 했는데 미리 넣고 수정해도 괜찮겠네요

2016-09-28 01:59 UTC, JeffGuKang commented on daily/01_Instagram/README.md
> +- Node.js / NPM
npm is lowercase.

2016-09-28 02:00 UTC, JeffGuKang commented
index.html 파일은 따로 날려주시는게 좋습니다 :) 
다른 분이 편집하실수가 있어서 conflicts날 확률이 높거든요.

2016-09-28 04:08 UTC, MuhunKim commented
@JeffGuKang 재리뷰 부탁드립니다. re-review request!

2016-09-28 06:37 UTC, JeffGuKang approved these changes

2016-09-28 06:42 UTC, merged