insta d team
kosslab-kr/kosshack2016 pull request #20
Opened 2016-09-27 17:38 UTC by cosmicboon

9월27일 데일리 @JeffGuKang

2016-09-27 17:43 UTC, mu-hun requested changes

2016-09-27 17:43 UTC, MuhunKim commented on daily/01_Instagram/README.md
> +<<<<<<< HEAD
Menual merge isn't Done!

수동 머지가 잘 안되었습니다.

2016-09-27 17:43 UTC, MuhunKim commented on daily/01_Instagram/README.md
> +>>>>>>> eda9977f4743e8ad307025b94800f9dcd0c7feb2
.

2016-09-27 17:43 UTC, MuhunKim commented on daily/01_Instagram/README.md
> +=======
.

2016-09-28 02:08 UTC, JeffGuKang requested changes
Do not use unnecessary spaces. 
Use `tab` for nested lists.

2016-09-28 02:08 UTC, JeffGuKang commented on daily/01_Instagram/README.md
> +>>>>>>> eda9977f4743e8ad307025b94800f9dcd0c7feb2
Delete unnecessary traces.

2016-09-28 02:08 UTC, JeffGuKang commented on daily/01_Instagram/README.md
> +  - Git 정리
Use `tab` for the nested list.

2016-09-28 02:08 UTC, JeffGuKang commented on daily/01_Instagram/README.md
> +  ## 2016년 9월 27일
Do not use unnecessary spaces.

2016-09-28 02:08 UTC, JeffGuKang commented on daily/01_Instagram/README.md
> +    - pr을 위한 프로세스 이해 및 실습
Use `tab`.

2016-09-28 18:49 UTC, closed without merging