9/30 daily update % Modify mistyping
kosslab-kr/kosshack2016 pull request #42
Opened 2016-09-30 18:17 UTC by choseungyoon

2016-09-30 18:18 UTC, JeffGuKang requested changes
Conflicts.

2016-09-30 18:51 UTC, choseungyoon commented
@JeffGuKang  Resolve conflicts

2016-10-01 01:46 UTC, MuhunKim commented on daily/01_Instagram/2016-09-30.md
> +	- 발표준비
@choseungyoon 팀장이 발표하는게 아니였나요??

2016-10-01 06:33 UTC, JeffGuKang approved these changes

2016-10-01 06:33 UTC, merged